import { getOctokit } from "../github-client.js";
import { getCountFromLinkHeader } from "../link-header.js";
import type {
  PullRequestCounts,
  PullRequestDetail,
  MergedPRSummary,
  CopilotAdoption,
} from "../types.js";
import type { GraphQLRepoData, GraphQLPRNode, CommitAuthorNode } from "./repo-graphql.js";

/**
 * Identify which AI tool authored a PR.
 * Handles Copilot (`copilot[bot]` / `copilot-swe-agent` / `Copilot` Bot),
 * Claude (`claude[bot]` / `claude[agent]` / `anthropic-code-agent`),
 * and Codex (`codex[bot]` / `codex[agent]` / `openai-code-agent`).
 * Returns null for humans and other bots.
 */
function getAIAuthorType(
  login: string,
  typeHint?: string,
): "copilot" | "claude" | "codex" | null {
  const lower = login.toLowerCase();
  if (lower === "copilot[bot]" || lower === "copilot-swe-agent" || (lower === "copilot" && typeHint === "Bot")) return "copilot";
  if (lower === "claude[bot]" || lower === "claude[agent]" || lower === "anthropic-code-agent") return "claude";
  if (lower === "codex[bot]" || lower === "codex[agent]" || lower === "openai-code-agent") return "codex";
  return null;
}

/**
 * Parse `Co-authored-by:` trailers in a commit message and return the AI tool
 * type if one is found, or null for a fully human commit.
 *
 * Matches:
 *  - `copilot-swe-agent[bot]` or `+Copilot@users.noreply.github.com` → "copilot"
 *  - `claude[bot]`, `claude[agent]`, or `anthropic-code-agent`  → "claude"
 *  - `codex[bot]`, `codex[agent]`, or `openai-code-agent`       → "codex"
 */
export function parseAICoAuthorType(
  message: string,
): "copilot" | "claude" | "codex" | null {
  let found: "copilot" | "claude" | "codex" | null = null;
  for (const line of message.split("\n")) {
    const lower = line.toLowerCase().trim();
    if (!lower.startsWith("co-authored-by:")) continue;
    if (lower.includes("copilot") || lower.includes("+copilot@")) return "copilot";
    if ((lower.includes("claude[bot]") || lower.includes("claude[agent]") || lower.includes("anthropic-code-agent")) && found === null) found = "claude";
    else if ((lower.includes("codex[bot]") || lower.includes("codex[agent]") || lower.includes("openai-code-agent")) && found === null) found = "codex";
  }
  return found;
}

/**
 * Detect AI tool authorship from a PR body.
 *
 * Checks (in order):
 *  1. `Co-authored-by:` trailers in the body text.
 *  2. Known prose signatures added by Copilot workspace / coding-agent PRs.
 *
 * Intentionally conservative — prose patterns use known structured phrases
 * rather than broad keyword matching to reduce false positives.
 */
export function parseAIBodySignature(
  body: string | null | undefined,
): "copilot" | "claude" | "codex" | null {
  if (!body) return null;
  const fromTrailer = parseAICoAuthorType(body);
  if (fromTrailer !== null) return fromTrailer;
  const lower = body.toLowerCase();
  if (
    lower.includes("suggested by copilot") ||
    lower.includes("generated by copilot") ||
    lower.includes("created by github copilot") ||
    lower.includes("copilot workspace")
  ) return "copilot";
  if (lower.includes("generated by claude") || lower.includes("created by claude")) return "claude";
  if (lower.includes("generated by codex") || lower.includes("openai codex")) return "codex";
  return null;
}

/**
 * Return the AI tool type for a commit author based on their GitHub login or
 * their noreply email address. Restricts email matching to `@users.noreply.github.com`
 * to avoid false-positives from regular user emails.
 */
function getAIAuthorTypeFromCommitAuthor(node: CommitAuthorNode): "copilot" | "claude" | "codex" | null {
  if (node.user) {
    const fromLogin = getAIAuthorType(node.user.login, node.user.__typename);
    if (fromLogin !== null) return fromLogin;
  }
  // Restrict to GitHub's noreply domain to avoid matching human email addresses.
  const email = node.email.toLowerCase();
  if (email.endsWith("@users.noreply.github.com")) {
    const local = email.split("@")[0] ?? "";
    if (local.includes("copilot")) return "copilot";
    if (local.includes("claude") || local.includes("anthropic")) return "claude";
    if (local.includes("codex") || local.includes("openai")) return "codex";
  }
  return null;
}

/**
 * Scan GraphQL commit-author nodes for the first AI co-author and return its
 * tool type, or null if all authors are human.
 *
 * Note: detection is best-effort — only the first 10 commits per PR are
 * fetched, so AI co-authorship beyond that window is not detected.
 */
function resolveAITypeFromCommitAuthors(
  commitNodes: GraphQLPRNode["commits"]["nodes"],
): "copilot" | "claude" | "codex" | null {
  for (const commitEntry of commitNodes) {
    for (const authorNode of (commitEntry?.commit?.authors?.nodes ?? [])) {
      if (!authorNode) continue;
      const type = getAIAuthorTypeFromCommitAuthor(authorNode);
      if (type !== null) return type;
    }
  }
  return null;
}

/**
 * Identify which AI tool authored or co-authored a PR.
 *
 * Resolution order (first non-null wins):
 *  1. PR author login
 *  2. Merge-commit `Co-authored-by:` trailers
 *  3. Individual commit authors (GraphQL `Commit.authors`, best-effort first 10 commits)
 *  4. PR body signatures (`Co-authored-by:` trailers + known prose patterns)
 */
function resolveAIType(
  login: string,
  typeHint: string | undefined,
  mergeCommitMessage?: string | null,
  commitNodes?: GraphQLPRNode["commits"]["nodes"],
  body?: string | null,
): "copilot" | "claude" | "codex" | null {
  const fromAuthor = getAIAuthorType(login, typeHint);
  if (fromAuthor !== null) return fromAuthor;
  if (mergeCommitMessage) {
    const fromMerge = parseAICoAuthorType(mergeCommitMessage);
    if (fromMerge !== null) return fromMerge;
  }
  if (commitNodes?.length) {
    const fromCommits = resolveAITypeFromCommitAuthors(commitNodes);
    if (fromCommits !== null) return fromCommits;
  }
  return parseAIBodySignature(body);
}
function isCopilotUser(login: string, typeHint?: string): boolean {
  const lower = login.toLowerCase();
  return lower === "copilot[bot]" || (lower === "copilot" && typeHint === "Bot");
}

/**
 * Extract issue numbers from a PR body that use closing keywords.
 * Matches: Fixes #123, closes #45, Resolves #9, etc.
 */
export function parseIssueRefs(body: string | null | undefined): number[] {
  if (!body) return [];
  const pattern = /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi;
  const nums = new Set<number>();
  let m: RegExpExecArray | null;
  while ((m = pattern.exec(body)) !== null) {
    nums.add(Number(m[1]));
  }
  return [...nums];
}

function isBotLogin(login: string): boolean {
  const lower = login.toLowerCase();
  return lower.endsWith("[bot]") || lower.endsWith("[agent]") ||
    lower === "copilot-swe-agent" || lower === "anthropic-code-agent" || lower === "openai-code-agent";
}

function hoursBetween(a: string, b: string): number {
  return Math.max(0, (new Date(b).getTime() - new Date(a).getTime()) / 3_600_000);
}

/**
 * Count open, closed and merged pull requests for a repository.
 *
 * Uses the list-pull-requests endpoint.  Open PRs are counted via the
 * Link header; closed PRs are paginated so we can separate merged from
 * unmerged.
 */
export async function collectPullRequestCounts(
  owner: string,
  repo: string
): Promise<PullRequestCounts> {
  const octokit = await getOctokit();

  try {
    // Open count via Link header (single request)
    const openRes = await octokit.rest.pulls.list({
      owner,
      repo,
      state: "open",
      per_page: 1,
    });
    const open = getCountFromLinkHeader(openRes);

    // Paginate closed PRs to distinguish merged from unmerged
    const closedPrs = await octokit.paginate(octokit.rest.pulls.list, {
      owner,
      repo,
      state: "closed",
      per_page: 100,
    });
    let merged = 0;
    let closed = 0;
    for (const pr of closedPrs) {
      if (pr.merged_at) merged++;
      else closed++;
    }

    return { open, closed, merged };
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 404 || status === 403) {
      if (status === 403) {
        console.warn(`  ⚠ pull-requests: skipping ${owner}/${repo}: access denied (403) — token may need SAML SSO authorization`);
      }
      return { open: 0, closed: 0, merged: 0 };
    }
    throw err;
  }
}

/**
 * Collect detailed metrics for the most recent merged PRs (up to `limit`).
 * Includes Copilot authorship/review detection.
 */
export async function collectPullRequestDetails(
  owner: string,
  repo: string,
  limit = 10
): Promise<PullRequestDetail[]> {
  const octokit = await getOctokit();

  // Get recent merged PRs
  let prs: Awaited<ReturnType<typeof octokit.rest.pulls.list>>["data"] = [];
  try {
    const res = await octokit.rest.pulls.list({
      owner,
      repo,
      state: "closed",
      sort: "updated",
      direction: "desc",
      per_page: limit,
    });
    prs = res.data;
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 403 || status === 404) {
      if (status === 403) {
        console.warn(`  ⚠ pr-details: skipping ${owner}/${repo}: access denied (403) — token may need SAML SSO authorization`);
      }
      return [];
    }
    throw err;
  }

  const mergedPrs = prs
    .filter((pr) => pr.merged_at !== null)
    .sort((a, b) => (b.merged_at! > a.merged_at! ? 1 : -1));

  const details: PullRequestDetail[] = [];
  for (const pr of mergedPrs) {
    try {
      const { data: detail } = await octokit.rest.pulls.get({
        owner,
        repo,
        pull_number: pr.number,
      });

      // Estimate actions minutes from check-suite run durations
      let actionsMinutes = 0;
      try {
        const { data: checkRuns } =
          await octokit.rest.checks.listForRef({
            owner,
            repo,
            ref: detail.head.sha,
            per_page: 100,
          });
        for (const run of checkRuns.check_runs) {
          if (run.started_at && run.completed_at) {
            const start = new Date(run.started_at).getTime();
            const end = new Date(run.completed_at).getTime();
            actionsMinutes += (end - start) / 60000;
          }
        }
      } catch {
        // Check runs may not be accessible; leave as 0
      }

      // Detect Copilot review
      let hasCopilotReview = false;
      try {
        const { data: reviews } = await octokit.rest.pulls.listReviews({
          owner,
          repo,
          pull_number: pr.number,
          per_page: 100,
        });
        hasCopilotReview = reviews.some(
          (r) => isCopilotUser(r.user?.login ?? "", r.user?.type),
        );
      } catch {
        // Reviews may not be accessible
      }

      const authorLogin = pr.user?.login ?? "unknown";

      // Check merge commit message for AI co-author trailers
      let mergeCommitMessage: string | null = null;
      if (detail.merge_commit_sha) {
        try {
          const { data: mergeCommit } = await octokit.rest.git.getCommit({
            owner, repo, commit_sha: detail.merge_commit_sha,
          });
          mergeCommitMessage = mergeCommit.message;
        } catch {
          // Merge commit may not be accessible; co-author check skipped
        }
      }
      const aiType = resolveAIType(authorLogin, pr.user?.type, mergeCommitMessage);

      details.push({
        number: pr.number,
        title: pr.title,
        state: pr.merged_at ? "merged" : "closed",
        createdAt: pr.created_at,
        author: authorLogin,
        isCopilotAuthored: aiType !== null,
        aiAuthorType: aiType ?? undefined,
        hasCopilotReview,
        linesAdded: detail.additions,
        linesDeleted: detail.deletions,
        commentCount: detail.comments + detail.review_comments,
        commitCount: detail.commits,
        actionsMinutes: Math.round(actionsMinutes * 100) / 100,
        timeToMergeHours: pr.merged_at
          ? Math.round(hoursBetween(pr.created_at, pr.merged_at) * 100) / 100
          : undefined,
        mergedAt: pr.merged_at ?? undefined,
      });
    } catch {
      // Skip PRs we cannot fetch details for
    }
  }
  return details;
}

/**
 * Collect an enriched timeline of merged PRs going back up to ~13 months.
 * Paginates through closed PRs (up to maxPages×100 entries) using only the
 * cheap pulls.list call — no per-PR detail fetches.
 *
 * Each entry includes author, timing, and issue-reference metadata extracted
 * from the list response, which is enough for cycle-time charts, actor
 * breakdowns, and Copilot adoption KPIs without extra API calls.
 */
export async function collectMergedPRTimeline(
  owner: string,
  repo: string,
  maxPages = 10
): Promise<MergedPRSummary[]> {
  const octokit = await getOctokit();
  const timeline: MergedPRSummary[] = [];
  for (let page = 1; page <= maxPages; page++) {
    try {
      const res = await octokit.rest.pulls.list({
        owner,
        repo,
        state: "closed",
        sort: "updated",
        direction: "desc",
        per_page: 100,
        page,
      });
      for (const pr of res.data) {
        if (!pr.merged_at) continue;
        const authorLogin = pr.user?.login ?? "unknown";
        const aiType = getAIAuthorType(authorLogin, pr.user?.type);
        timeline.push({
          number: pr.number,
          createdAt: pr.created_at,
          mergedAt: pr.merged_at,
          author: authorLogin,
          isBotAuthor: pr.user?.type === "Bot" || isBotLogin(authorLogin),
          isCopilotAuthored: aiType !== null,
          aiAuthorType: aiType ?? undefined,
          timeToMergeHours:
            Math.round(hoursBetween(pr.created_at, pr.merged_at) * 100) / 100,
          closesIssues: parseIssueRefs(pr.body),
        });
      }
      if (res.data.length < 100) break; // reached the last page
    } catch (err: unknown) {
      const status = (err as { status?: number }).status;
      if (status === 403 || status === 404) break;
      throw err;
    }
  }
  return timeline.sort((a, b) => (b.mergedAt > a.mergedAt ? 1 : -1));
}

/**
 * Compute Copilot adoption metrics from the merged PR timeline and details.
 */
export function computeCopilotAdoption(
  timeline: MergedPRSummary[],
  details: PullRequestDetail[],
): CopilotAdoption {
  return {
    copilotAuthoredPRs: timeline.filter((p) => p.isCopilotAuthored).length,
    copilotReviewedPRs: details.filter((p) => p.hasCopilotReview).length,
    totalMergedPRs: timeline.length,
    totalDetailedPRs: details.length,
  };
}

// ── GraphQL-based pure transforms ─────────────────────────────────────────────

/**
 * Derive PullRequestCounts from pre-fetched GraphQL repository data.
 * No API calls.
 */
export function buildPullRequestCounts(data: GraphQLRepoData): PullRequestCounts {
  return {
    open: data.openPRCount,
    closed: data.closedPRCount,
    merged: data.mergedPRCount,
  };
}

/**
 * Build a MergedPRSummary timeline from pre-fetched GraphQL PR nodes.
 * Only includes MERGED nodes. No API calls.
 */
export function buildMergedPRTimeline(nodes: GraphQLPRNode[]): MergedPRSummary[] {
  const timeline: MergedPRSummary[] = [];
  for (const node of nodes) {
    if (node.state !== "MERGED" || !node.mergedAt) continue;
    const authorLogin = node.author?.login ?? "unknown";
    const isBot = node.author?.__typename === "Bot" || isBotLogin(authorLogin);
    const aiType = resolveAIType(authorLogin, node.author?.__typename, node.mergeCommit?.message, node.commits.nodes, node.body);
    timeline.push({
      number: node.number,
      createdAt: node.createdAt,
      mergedAt: node.mergedAt,
      author: authorLogin,
      isBotAuthor: isBot,
      isCopilotAuthored: aiType !== null,
      aiAuthorType: aiType ?? undefined,
      timeToMergeHours:
        Math.round(hoursBetween(node.createdAt, node.mergedAt) * 100) / 100,
      closesIssues: parseIssueRefs(node.body),
      linesAdded: node.additions,
      linesDeleted: node.deletions,
    });
  }
  return timeline.sort((a, b) => (b.mergedAt > a.mergedAt ? 1 : -1));
}

/**
 * Build PullRequestDetail[] from pre-fetched GraphQL PR nodes.
 * Only includes MERGED nodes (up to `limit`). For each PR, calls
 * `checks.listForRef` to compute actionsMinutes; all other data comes
 * from the pre-fetched nodes.
 */
export async function collectPullRequestDetailsFromNodes(
  owner: string,
  repo: string,
  nodes: GraphQLPRNode[],
  limit = 10
): Promise<PullRequestDetail[]> {
  const octokit = await getOctokit();

  const mergedNodes = nodes
    .filter((n) => n.state === "MERGED" && n.mergedAt)
    .sort((a, b) => (b.mergedAt! > a.mergedAt! ? 1 : -1))
    .slice(0, limit);

  const details: PullRequestDetail[] = [];
  for (const node of mergedNodes) {
    let actionsMinutes = 0;
    try {
      const { data: checkRuns } = await octokit.rest.checks.listForRef({
        owner,
        repo,
        ref: node.headRefOid,
        per_page: 100,
      });
      for (const run of checkRuns.check_runs) {
        if (run.started_at && run.completed_at) {
          const start = new Date(run.started_at).getTime();
          const end = new Date(run.completed_at).getTime();
          actionsMinutes += (end - start) / 60000;
        }
      }
    } catch {
      // Check runs may not be accessible; leave as 0
    }

    const authorLogin = node.author?.login ?? "unknown";
    const reviewerLogins = node.reviews.nodes
      .map((r) => r.author?.login ?? "")
      .filter(Boolean);
    const hasCopilotReview = reviewerLogins.some(
      (l) => l.toLowerCase() === "copilot[bot]" || l.toLowerCase() === "copilot"
    );
    const aiType = resolveAIType(authorLogin, node.author?.__typename, node.mergeCommit?.message, node.commits.nodes, node.body);

    details.push({
      number: node.number,
      title: node.title,
      state: "merged",
      createdAt: node.createdAt,
      author: authorLogin,
      isCopilotAuthored: aiType !== null,
      aiAuthorType: aiType ?? undefined,
      hasCopilotReview,
      linesAdded: node.additions,
      linesDeleted: node.deletions,
      commentCount: node.comments.totalCount + node.reviewThreads.totalCount,
      commitCount: node.commits.totalCount,
      actionsMinutes: Math.round(actionsMinutes * 100) / 100,
      timeToMergeHours: node.mergedAt
        ? Math.round(hoursBetween(node.createdAt, node.mergedAt) * 100) / 100
        : undefined,
      mergedAt: node.mergedAt ?? undefined,
    });
  }
  return details;
}

/**
 * Extract reviewer logins from a list of GraphQL PR nodes.
 * Returns a Set of unique non-bot reviewer logins.
 */
export function extractReviewerLogins(nodes: GraphQLPRNode[]): Set<string> {
  const reviewers = new Set<string>();
  for (const node of nodes) {
    for (const review of node.reviews.nodes) {
      const login = review.author?.login;
      if (login) reviewers.add(login);
    }
  }
  return reviewers;
}
